//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visco_Web_Scrape_v2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Visco_Web_Scrape_v2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url contains unreadable extension.
        /// </summary>
        internal static string BadExtension {
            get {
                return ResourceManager.GetString("BadExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Required.
        /// </summary>
        internal static string ConfirmationRequired {
            get {
                return ResourceManager.GetString("ConfirmationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the search? If you save the results after canceling early, results so far will potenitally overwrite existing results..
        /// </summary>
        internal static string ConfirmCancelCrawl {
            get {
                return ResourceManager.GetString("ConfirmCancelCrawl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear the results of previous web crawls?.
        /// </summary>
        internal static string ConfirmClearResults {
            get {
                return ResourceManager.GetString("ConfirmClearResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset the website and keyword lists?.
        /// </summary>
        internal static string ConfirmClearWebAndKeys {
            get {
                return ResourceManager.GetString("ConfirmClearWebAndKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the following keyword from the list?
        ///.
        /// </summary>
        internal static string ConfirmDeleteKeyword {
            get {
                return ResourceManager.GetString("ConfirmDeleteKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the following recipient from the list?
        ///.
        /// </summary>
        internal static string ConfirmDeleteRecipient {
            get {
                return ResourceManager.GetString("ConfirmDeleteRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the following website from the list?
        ///.
        /// </summary>
        internal static string ConfirmDeleteWebsite {
            get {
                return ResourceManager.GetString("ConfirmDeleteWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to send an email of the incomplete search?.
        /// </summary>
        internal static string ConfirmSendIncompleteSearch {
            get {
                return ResourceManager.GetString("ConfirmSendIncompleteSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After entering in the desired websites (domains) to search through with specified keywords, this app will systematically go through all the domains following certain rules and settings.  These are both pre-defined and user selected and influence how the searcher operates.  The search can be cancelled at any time or allowed to run to completion, but regardless the results can be exported for viewing later on and even sent to a list of people through email.  The searcher is powered by the Abot libray and expo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following domain search completed with an error:
        ///.
        /// </summary>
        internal static string DomainCrawlError {
            get {
                return ResourceManager.GetString("DomainCrawlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occurred.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while starting the excel file creation.  Please try again.
        /// </summary>
        internal static string ExcelWorkerIsNull {
            get {
                return ResourceManager.GetString("ExcelWorkerIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not yet implemented, please either return to the main form or choose a different setting.
        /// </summary>
        internal static string FeatureNotImplemented {
            get {
                return ResourceManager.GetString("FeatureNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just a Heads Up.
        /// </summary>
        internal static string HeadsUp {
            get {
                return ResourceManager.GetString("HeadsUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected keyword does not exist in the records.
        /// </summary>
        internal static string KeywordNotFound {
            get {
                return ResourceManager.GetString("KeywordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to send an email.  Please contact the developer..
        /// </summary>
        internal static string MailSendError {
            get {
                return ResourceManager.GetString("MailSendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors can occur if results list contains results that do not match the website list..
        /// </summary>
        internal static string MismatchWarning {
            get {
                return ResourceManager.GetString("MismatchWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results file was found, would you like to create a new one?.
        /// </summary>
        internal static string NoResultsFileFound {
            get {
                return ResourceManager.GetString("NoResultsFileFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No settings file was found, would you like to create a new one?.
        /// </summary>
        internal static string NoSettingsFound {
            get {
                return ResourceManager.GetString("NoSettingsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected recipient does not exist in the records.
        /// </summary>
        internal static string RecipientNotFound {
            get {
                return ResourceManager.GetString("RecipientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.bin.
        /// </summary>
        internal static string ResultsFileName {
            get {
                return ResourceManager.GetString("ResultsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.bin.
        /// </summary>
        internal static string SettingsFileName {
            get {
                return ResourceManager.GetString("SettingsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please contact the developed with detailed steps on how to replicate this error so it may be fixed..
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url contains a hard-coded blacklist word for increased search speed.
        /// </summary>
        internal static string UrlFiltered {
            get {
                return ResourceManager.GetString("UrlFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.6.5 beta.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap visco_logo {
            get {
                object obj = ResourceManager.GetObject("visco_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected website does not exist in the records.
        /// </summary>
        internal static string WebsiteNotFound {
            get {
                return ResourceManager.GetString("WebsiteNotFound", resourceCulture);
            }
        }
    }
}
