//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visco_Web_Scrape.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Visco_Web_Scrape.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem loading the keyword list from the settings file.  Would you like to create a new keyword list?.
        /// </summary>
        internal static string KeywordListErrorContent {
            get {
                return ResourceManager.GetString("KeywordListErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving filter data.
        /// </summary>
        internal static string KeywordListErrorTitle {
            get {
                return ResourceManager.GetString("KeywordListErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings file was either not found or was incorrectly formatted, would you like to create a new one?.
        /// </summary>
        internal static string SettingsFileNotFound {
            get {
                return ResourceManager.GetString("SettingsFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading Settings.
        /// </summary>
        internal static string SettingsFileNotFoundCaption {
            get {
                return ResourceManager.GetString("SettingsFileNotFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During step one, the web crawler is active and the pages have not yet been scraped.  The web crawler follows links on the root page and compares the content on those pages with keywords that are in Step One list.  In addition, if Step Two and Three keywords are supplied, it will search for parsable content on the page..
        /// </summary>
        internal static string StepOneHelpContent {
            get {
                return ResourceManager.GetString("StepOneHelpContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step One Help.
        /// </summary>
        internal static string StepOneHelpTitle {
            get {
                return ResourceManager.GetString("StepOneHelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During Step Two, the crawler has finished its work and the page is being prepared for scraping.  If keywords are supplied for filtering here or in Step Three, the scraper will attempt to parse the page and extract information in a meaningful way based on very specific rules that follow the keywords supplied.
        ///
        ///For example, you can specify to search for a dollar sign and the scraper will intelligently extract data that has to do with dollar figures, such as the amount of the grant..
        /// </summary>
        internal static string StepTwoHelpContent {
            get {
                return ResourceManager.GetString("StepTwoHelpContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Two Help.
        /// </summary>
        internal static string StepTwoHelpTitle {
            get {
                return ResourceManager.GetString("StepTwoHelpTitle", resourceCulture);
            }
        }
    }
}
