using System;
using System.IO;
using System.Net;
using System.Net.Mail;
using System.Net.Mime;
using System.Windows.Forms;
using Visco_Web_Scrape_v2.Scripts;
using Visco_Web_Scrape_v2.Scripts.Helpers;


namespace Visco_Web_Scrape_v2.Forms {

	public partial class EmailProgress : Form {

		public Configuration Config;

		private string fileName;

		public EmailProgress(Configuration config) {
			InitializeComponent();

			Config = config;
		}

		private bool PrepareExcelDocument() {
			lblCurrentStatus.Text = "Generating excel file";
			var excelExport = new ResultViewer(Config);
			excelExport.ExportToExcel(true);
			excelExport.Close();

			var date = Config.LastCrawl.Date;
			fileName = Reference.Files.AppFileDirectory + "Results_"
				+ date.Month + date.Day + date.Year + ".xlsx";

			if (File.Exists(fileName)) {
				lblCurrentStatus.Text = "File saved";
				return true;
			} else {
				lblCurrentStatus.Text = "Error saving file";
				return false;
			}
		}

		private void SendEmail() {
			try {
				var client = new SmtpClient {
					Host = "Smtp.Gmail.com",
					Port = 587,
					EnableSsl = true,
					Timeout = 10000,
					DeliveryMethod = SmtpDeliveryMethod.Network,
					UseDefaultCredentials = false,
					Credentials = new NetworkCredential("viscograntbot@gmail.com", "DarkstoneConcepts")
				};

				// Create the attachment
				var attachment = new Attachment(fileName, MediaTypeNames.Application.Octet);
				var disposition = attachment.ContentDisposition;
				disposition.CreationDate = File.GetCreationTime(fileName);
				disposition.ModificationDate = File.GetLastWriteTime(fileName);
				disposition.ReadDate = File.GetLastAccessTime(fileName);

				var body = "This email was automatically generated by the Visco Grant Search application on " +
					DateTime.Now.ToLocalTime().ToShortDateString() +
					" at " + DateTime.Now.ToLocalTime().ToShortTimeString() +
					" and contains the results of the search in an excel file that is attached.";
				var subject = "Grant Search Results";

				// Create the message
				var message = new MailMessage {
					From = new MailAddress("viscograntbot@gmail.com", "Visco Grant Bot"),
					Body = body,
					Subject = subject
				};

				progressBar1.Maximum = Config.Recipients.Count;

				// Send the message to each recipient
				for (int index = 0; index < Config.Recipients.Count; index++) {
					progressBar1.Value++;
					var recipient = Config.Recipients[index];
					LogHelper.Debug("Preparing message for " + recipient.Name);
					message.To.Clear();
					message.To.Add(new MailAddress(recipient.Address, recipient.Name));
					message.Attachments.Add(attachment);

					LogHelper.Debug("Sending message to " + recipient.Name + " at " + recipient.Address);
					lblRecipientCount.Text = (index + 1) + " of " + Config.Recipients.Count;
					client.Send(message);
				}
			} catch (Exception e) {
				LogHelper.Error(e.Message);
				LogHelper.Trace(e.StackTrace);
			}
		}

		private void EmailProgress_Shown(object sender, EventArgs e) {
			if (PrepareExcelDocument()) {
				SendEmail();
			} else {
				MessageBox.Show(Reference.Messages.MailSendError, Reference.Messages.Error, MessageBoxButtons.OK, MessageBoxIcon.Error);
			}
		}
	}

}