using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Net.Mail;
using System.Net.Mime;
using System.Threading;
using System.Windows.Forms;
using Visco_Web_Scrape_v2.Properties;
using Visco_Web_Scrape_v2.Scripts;
using Visco_Web_Scrape_v2.Scripts.Helpers;
using Visco_Web_Scrape_v2.Search.Items;

namespace Visco_Web_Scrape_v2.Forms {

	public partial class EmailProgress : Form {

		public Configuration Config;
		public CombinedResults Results;

		private string fileName;
		private readonly List<Recipient> sendToList;

		public EmailProgress(Configuration config, CombinedResults res) {
			InitializeComponent();

			Config = config;
			Results = res;

			sendToList = new List<Recipient>();
			sendToList.AddRange(this.Config.Recipients);
		}

		private bool PrepareExcelDocument() {
			return false;
		}

		private void SendEmail() {
			try {
				var client = new SmtpClient {
					Host = "Smtp.Gmail.com",
					Port = 587,
					EnableSsl = true,
					Timeout = 10000,
					DeliveryMethod = SmtpDeliveryMethod.Network,
					UseDefaultCredentials = false,
					Credentials = new NetworkCredential("viscograntbot@gmail.com", "DarkstoneConcepts")
				};

				// Create the attachment
				var attachment = new Attachment(fileName, MediaTypeNames.Application.Octet);
				var disposition = attachment.ContentDisposition;
				disposition.CreationDate = File.GetCreationTime(fileName);
				disposition.ModificationDate = File.GetLastWriteTime(fileName);
				disposition.ReadDate = File.GetLastAccessTime(fileName);

				var body = "This email was automatically generated by the Visco Grant Search application on " +
					DateTime.Now.ToLocalTime().ToShortDateString() +
					" at " + DateTime.Now.ToLocalTime().ToShortTimeString() +
					" and contains the results of the search in an excel file that is attached.";
				var subject = "Grant Search Results";

				// Create the message
				var message = new MailMessage {
					From = new MailAddress("viscograntbot@gmail.com", "Visco Grant Bot"),
					Body = body,
					Subject = subject
				};

				progressBar1.Maximum = Config.Recipients.Count;

				// Send the message to each recipient
				foreach (var recipient in Config.Recipients) {
					progressBar1.Value++;
					LogHelper.Debug("Preparing message for " + recipient.Name);
					message.To.Clear();
					message.To.Add(new MailAddress(recipient.Address, recipient.Name));
					message.Attachments.Add(attachment);

					LogHelper.Debug("Sending message to " + recipient.Name + " at " + recipient.Address);
					lblRecipientCount.Text = (sendToList.IndexOf(recipient) + 1) + " of " + sendToList.Count;
					client.Send(message);
				}
			} catch (Exception e) {
				LogHelper.Error(e.Message);
				LogHelper.Trace(e.StackTrace);
			}
		}

		private void EmailProgress_Shown(object sender, EventArgs e) {
			if (PrepareExcelDocument()) {
				SendEmail();
			} else {
				MessageBox.Show(Resources.MailSendError, Resources.Error, MessageBoxButtons.OK, MessageBoxIcon.Error);
			}
		}
	}

}